import type { APIRoute } from "astro";
import { SITE_URL } from "@/config";

function getRobotsTxt(sitemapURL: URL) {
  return `User-agent: *
Allow: /

# Prevent search engines from crawling private routes and backend management pages
Disallow: /write/
Disallow: /config/
Disallow: /api/

# Prevent crawling the internal resource directory generated by the framework compilation
Disallow: /_astro/
Disallow: /.vercel/

# Disable crawling of dynamic links with query parameters to avoid page weight dilution and duplicate indexing.
Disallow: /*?*

Sitemap: ${sitemapURL.href}`;
}

export const GET: APIRoute = ({ site }) => {
  // 自动回退域名兜底，且指向正确的自建 sitemap.xml
  const sitemapURL = new URL("sitemap.xml", site || SITE_URL);

  return new Response(getRobotsTxt(sitemapURL), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=86400, s-maxage=86400",
    },
  });
};
